title: ChickenPaella's blog
description: Lazy blog
theme: just-the-docs

url: https://chickenpaella.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
