title: ChickenPaella's blog
description: Lazy blog
theme: just-the-docs

url: https://chickenpaella.github.io
defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

